name: Analysis - SonarCloud

on:
  push:
    branches:
      - main
  pull_request:

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2

jobs:
  sonarcloud:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build ccache \
            libharfbuzz-dev libfribidi-dev libprotobuf-dev protobuf-compiler \
            libphysfs-dev nlohmann-json3-dev libpugixml-dev libfmt-dev \
            libopenal-dev libvorbis-dev libglew-dev libluajit-5.1-dev

      # Cache kompilatora ccache
      - name: Cache CCache
        uses: actions/cache@v4
        with:
          path: $HOME/.ccache
          key: ccache-${{ runner.os }}-${{ hashFiles('CMakeLists.txt', 'vcpkg.json', 'src/**/*.cpp', 'src/**/*.h') }}
          restore-keys: |
            ccache-${{ runner.os }}-

      # Cache danych analizy SonarCloud
      - name: Cache SonarCloud analysis data
        uses: actions/cache@v4
        with:
          path: $HOME/.cfamily
          key: sonar-cfamily-${{ runner.os }}-${{ hashFiles('CMakeLists.txt', 'vcpkg.json', 'src/**/*.cpp', 'src/**/*.h') }}
          restore-keys: |
            sonar-cfamily-${{ runner.os }}-

      # Cache paczek SonarCloud
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: $HOME/.sonar/cache
          key: sonar-packages-${{ runner.os }}
          restore-keys: |
            sonar-packages-${{ runner.os }}-

      # Setup vcpkg na stabilnym commicie
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 5b1214315250939257ef5d62ecdcbca18cf4fb1c
          vcpkgJsonGlob: vcpkg.json
          vcpkgConfigurationJsonGlob: vcpkg-configuration.json
          runVcpkgInstall: true

      # Kompilacja i wygenerowanie compile_commands.json
      - name: Build & Generate compilation database
        run: |
          cmake -S . -B build \
            -GNinja \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" \
            -DCMAKE_BUILD_TYPE=Debug \
            -DOTC_ENABLE_TTF=ON -DOTC_ENABLE_HARFBUZZ=ON -DOTC_ENABLE_FRIBIDI=ON \
            -DOPTIONS_ENABLE_CCACHE=ON \
            -DSPEED_UP_BUILD_UNITY=OFF
          cmake --build build --parallel
          cp build/compile_commands.json .

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=PtakuPL_testyy
            -Dsonar.organization=ptakupl
            -Dsonar.sources=src
            -Dsonar.cfamily.compile-commands=compile_commands.json
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
