name: build-windows

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - "**/*.md"
  pull_request:

concurrency:
  group: windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static
      VCPKG_FEATURE_FLAGS: manifests,binarycaching
      VCPKG_BINARY_SOURCES: clear;x-gha,readwrite
      CMAKE_BUILD_PARALLEL_LEVEL: 8

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup MSVC (VS 2022)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Override VCPKG_ROOT to workspace path
        shell: pwsh
        run: |
          $root = Join-Path $env:GITHUB_WORKSPACE 'vcpkg'
          echo "VCPKG_ROOT=$root" >> $env:GITHUB_ENV
          Write-Host "Using VCPKG_ROOT = $root"

      - name: Setup vcpkg (full clone + bootstrap)
        shell: pwsh
        run: |
          if (Test-Path "$env:VCPKG_ROOT") {
            Write-Host "Cleaning existing VCPKG_ROOT at $env:VCPKG_ROOT"
            Remove-Item -Recurse -Force "$env:VCPKG_ROOT"
          }
          git clone https://github.com/microsoft/vcpkg "$env:VCPKG_ROOT"
          git -C "$env:VCPKG_ROOT" fetch --force --tags --prune origin
          & "$env:VCPKG_ROOT\bootstrap-vcpkg.bat"
          & "$env:VCPKG_ROOT\vcpkg.exe" version

      - name: Cache vcpkg artifacts
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.VCPKG_ROOT }}\installed
            ${{ env.VCPKG_ROOT }}\downloads
          key: vcpkg-${{ env.VCPKG_DEFAULT_TRIPLET }}-${{ hashFiles('**/vcpkg.json','**/vcpkg-configuration.json','**/vcpkg-lock.json') }}
          restore-keys: |
            vcpkg-${{ env.VCPKG_DEFAULT_TRIPLET }}-

      - name: vcpkg install (manifest mode)
        shell: pwsh
        run: |
          & "$env:VCPKG_ROOT\vcpkg.exe" install --triplet $env:VCPKG_DEFAULT_TRIPLET
          & "$env:VCPKG_ROOT\vcpkg.exe" list

      - name: Configure (CMake - VS generator)
        shell: pwsh
        run: |
          cmake -S . -B build `
            -G "Visual Studio 17 2022" -A x64 `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT\scripts\buildsystems\vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET=${{ env.VCPKG_DEFAULT_TRIPLET }} `
            -DCMAKE_BUILD_TYPE=Release `
            -DOTC_ENABLE_TTF=ON -DOTC_ENABLE_HARFBUZZ=ON -DOTC_ENABLE_FRIBIDI=ON `
            -DCMAKE_VERBOSE_MAKEFILE=ON

      - name: Build (Release)
        shell: pwsh
        run: cmake --build build --config Release --parallel

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: otclient-windows-x64
          path: |
            build/**/Release/*.exe
            build/**/client.exe
            build/bin/**
          if-no-files-found: warn

      - name: Upload CMake logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cmake-logs-windows
          path: |
            build/CMakeFiles/CMakeOutput.log
            build/CMakeFiles/CMakeError.log
          if-no-files-found: warn
