name: build-linux

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - "**/*.md"
  pull_request:

concurrency:
  group: linux-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VCPKG_BUILD_TYPE: release
      VCPKG_DEFAULT_TRIPLET: x64-linux
      VCPKG_DEFAULT_HOST_TRIPLET: x64-linux
      VCPKG_FEATURE_FLAGS: manifests,binarycaching
      VCPKG_BINARY_SOURCES: clear;x-gha,readwrite
      CMAKE_BUILD_PARALLEL_LEVEL: 2
      MAKEFLAGS: -j 2

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false   # nie oczekujemy submodułu vcpkg/

      - name: Install base build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config

      - name: Install CMake + Ninja
        uses: lukka/get-cmake@latest

      # <<< KLUCZOWY KROK: poprawione ustawienia run-vcpkg >>>
      - name: Setup vcpkg (pin + manifest, bez submodułu)
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitURL: https://github.com/microsoft/vcpkg.git
          vcpkgGitCommitId: b322346fe03b0d04283f9daf05fecc0c8f64d6f
          # NIE podajemy vcpkgDirectory – akcja sama sklonuje vcpkg po SHA
          runVcpkgInstall: true
          # wskaż dokładnie jeden manifest (root)
          vcpkgJsonGlob: 'vcpkg.json'
          vcpkgConfigurationJsonGlob: 'vcpkg-configuration.json'
          # ignoruj nadmiarowe manifesty/overlay-ports (jak w Twoich logach)
          vcpkgJsonIgnores: "['**/vcpkg/**', '**/browser/overlay-ports/**']"
          # zachowuję Twoje ustawienia:
          doNotUpdateVcpkg: false
          doNotCache: true
          useShell: true
          runVcpkgFormatString: "[`install`, `--recurse`, `--clean-after-build`, `--x-install-root`, `$[env.VCPKG_INSTALLED_DIR]`, `--triplet`, `$[env.VCPKG_DEFAULT_TRIPLET]`]"
          logCollectionRegExps: "\s*\"(.+CMakeOutput\.log)\"\.\s*;\s*\"(.+CMakeError\.log)\"\.\s*;\s*(.+out\.log)\s*;\s+(.+err\.log)\s*;\s*(.+vcpkg.+\.log)\s*"

      - name: Configure (CMake + vcpkg toolchain)
        run: >
          cmake -S . -B build
          -G "Ninja"
          -DCMAKE_TOOLCHAIN_FILE="${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
          -DVCPKG_TARGET_TRIPLET="${VCPKG_DEFAULT_TRIPLET}"
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_VERBOSE_MAKEFILE=ON

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: linux-release-${{ github.run_number }}
          path: |
            build/**
          if-no-files-found: warn

      - name: Upload CMake logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cmake-logs-linux
          path: |
            build/CMakeFiles/CMakeOutput.log
            build/CMakeFiles/CMakeError.log
          if-no-files-found: warn
